name: tindog
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  app_ui:
    path: packages/app_ui
  auth_repository:
    path: packages/auth_repository
  core:
    path: packages/core
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  flutter_bloc: ^8.1.6
  firebase_core: ^3.1.0
  equatable: ^2.0.5
  permission_handler: ^11.3.1
  tindog_repository:
    path: packages/tindog_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true