name: tindog_data_source
description: Data source of Tindog
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  cloud_firestore: ^5.0.2
  cloud_functions: ^5.0.2
  equatable: ^2.0.5
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  json_annotation: ^4.9.0
  location: ^6.0.2

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
