name: app_ui
description: "UI package for Tindog"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  vector_graphics: ^1.1.11+1

dev_dependencies:
  build_runner: ^2.4.11
  cupertino_icons: ^1.0.6
  flutter_gen_runner: ^5.5.0+1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true
      directory_path_enabled: true
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - ./assets/images/
    - ./assets/icons/
    - ./assets/animations/
  fonts:
    - family: Josefin Slab
      fonts:
        - asset: ./assets/fonts/JosefinSlab-Italic-VariableFont_wght.ttf
          style: italic
        - asset: ./assets/fonts/JosefinSlab-VariableFont_wght.ttf